# Web Scraping - fundamentus.com

In [1]:
!pip install selenium
!pip install webdriver-manager

Collecting selenium
  Obtaining dependency information for selenium from https://files.pythonhosted.org/packages/fc/df/a8972c41279fc9e9404cad87bc1f4d6d3d824b84c5c072dca0e986a89680/selenium-4.14.0-py3-none-any.whl.metadata
  Downloading selenium-4.14.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\dudiz\anaconda3\lib\site-packages (from selenium) (1.26.16)
Collecting trio~=0.17 (from selenium)
  Obtaining dependency information for trio~=0.17 from https://files.pythonhosted.org/packages/a3/dd/b61fa61b186d3267ef3903048fbee29132963ae762fb70b08d4a3cd6f7aa/trio-0.22.2-py3-none-any.whl.metadata
  Downloading trio-0.22.2-py3-none-any.whl.metadata (4.7 kB)
Collecting trio-websocket~=0.9 (from selenium)
  Obtaining dependency information for trio-websocket~=0.9 from https://files.pythonhosted.org/packages/48/be/a9ae5f50cad5b6f85bd2574c2c923730098530096e170c1ce7452394d7aa/trio_websocket-0.11.1-py3-none-any.whl.metadata
  Downloading trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\dudiz\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: attrs>=20.1.0 in c:\users\dudiz\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\dudiz\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\dudiz\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Collecting outcome (from trio~=0.17->selenium)
  Obtaining dependency information for outcome from https://files.pythonhosted.org/packages/55/8b/5ab7257531a5d830fc8000c476e63c935488d74609b50f9384a643ec0a62/outcome-1.3.0.post0-py2.py3-none-any.whl.metadata
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio in c:\users\dudiz\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\dudiz\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\dudiz\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\dudiz\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ---------------------------------------- 0.0/58.3 kB ? eta -:--:--
     ----------------------------------- ---- 51.2/58.3 kB 2.7 MB/s eta 0:00:01
     -------------------------------------- 58.3/58.3 kB 280.8 kB/s eta 0:00:00
Downloading selenium-4.14.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB 9.3 MB/s eta 0:00:02
   -- ------------------------------------- 0.6/9.9 MB 8.1 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/9.9 MB 7.5 MB/s eta 0:00:02
   ------ --------------------------------- 1.7/9.9 MB 9.9 MB/s eta 0:00:01
   ------- -------------------------------- 1.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------- ----------------------------- 2.7/9.9 MB 10.0 MB/s eta 0:00:01
   ------------ --------------------------- 3.1/9.9 MB 9.9 MB/s eta 0:00:01
   -------------- ------------------------- 3.6/9.9 MB 10.0 MB/s eta 0:00:01
   ---------------- ----------------------- 4.2/9.9 MB 10.2 MB/s eta 0:00:01
   ------------------ --------------------- 4.7/9.9 MB 10.3 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/9.9 MB 10.1 MB/s eta 0:00:01
   ---------------------- ----------------- 5.7/9.9 MB 10.4 MB/s eta 0:00:01
   ------------------------ --------------- 6.1/9.9 MB 10.2 MB/s eta 0:00:01
   -------------------------- ------------- 6.7/9.9 MB 10.4 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 10.3 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 10.3 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/9.9 MB 10.0 MB/s eta 0:00:01
   --------------------------------- ------ 8.3/9.9 MB 10.0 MB/s eta 0:00:01
   ---------------------------------- ----- 8.5/9.9 MB 9.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.9/9.9 MB 9.6 MB/s eta 0:00:01
   ------------------------------------- -- 9.4/9.9 MB 9.7 MB/s eta 0:00:01
   -------------------------------------- - 9.7/9.9 MB 9.7 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 6.0 MB/s eta 0:00:00
Downloading trio-0.22.2-py3-none-any.whl (400 kB)
   ---------------------------------------- 0.0/400.2 kB ? eta -:--:--
   ---------------------------------------  399.4/400.2 kB 8.3 MB/s eta 0:00:01
   ---------------------------------------  399.4/400.2 kB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 400.2/400.2 kB 4.1 MB/s eta 0:00:00
Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Installing collected packages: outcome, h11, wsproto, trio, trio-websocket, selenium
Successfully installed h11-0.14.0 outcome-1.3.0.post0 selenium-4.14.0 trio-0.22.2 trio-websocket-0.11.1 wsproto-1.2.0
Collecting webdriver-manager
  Obtaining dependency information for webdriver-manager from https://files.pythonhosted.org/packages/b1/51/b5c11cf739ac4eecde611794a0ec9df420d0239d51e73bc19eb44f02b48b/webdriver_manager-4.0.1-py2.py3-none-any.whl.metadata
  Downloading webdriver_manager-4.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in c:\users\dudiz\anaconda3\lib\site-packages (from webdriver-manager) (2.31.0)
Collecting python-dotenv (from webdriver-manager)
  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Requirement already satisfied: packaging in c:\users\dudiz\anaconda3\lib\site-packages (from webdriver-manager) (23.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dudiz\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dudiz\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dudiz\anaconda3\lib\site-packages (from requests->webdriver-manager) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dudiz\anaconda3\lib\site-packages (from requests->webdriver-manager) (2023.7.22)
Downloading webdriver_manager-4.0.1-py2.py3-none-any.whl (27 kB)
Installing collected packages: python-dotenv, webdriver-manager
Successfully installed python-dotenv-1.0.0 webdriver-manager-4.0.1

O selenium é uma ferramenta poderosa para controlar um navegador web automatizado, enquanto o webdriver-manager ajuda a gerenciar os drivers necessários para controlar diferentes navegadores.

In [2]:
# Importa a classe 'webdriver' do módulo 'selenium' para interagir com um navegador web
from selenium import webdriver

# Importa a classe 'Service' do módulo 'selenium.webdriver.chrome.service' para configurar o serviço do ChromeDriver
from selenium.webdriver.chrome.service import Service

# Importa a função 'ChromeDriverManager' do módulo 'webdriver_manager.chrome' para gerenciar o driver do Chrome
from webdriver_manager.chrome import ChromeDriverManager

# Importa o pacote 'pandas' e o apelida como 'pd' para facilitar o uso
import pandas as pd

In [6]:
driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()))
driver.get('https://www.fundamentus.com.br/resultado.php')

- A primeira linha inicializa o driver do Chrome. Ela utiliza o **ChromeDriverManager** para baixar e configurar automaticamente o driver adequado para o seu ambiente, e o **Service** é usado para especificar a configuração do serviço do Chrome.

- A segunda linha abre o navegador Chrome e navega até a URL especificada ('https://www.fundamentus.com.br/resultado.php'). Isso significa que o navegador irá carregar a página inicial do site **"Fundamentus"**.

## Mapear o processo de coleta de dados no site

Nessa parte é necessário inspecionar o site para encontrar o local da tabela

In [7]:
# Define o caminho XPath para a tabela desejada
local_tabela = '/html/body/div[1]/div[2]/table'

# Encontra o elemento da página web usando o XPath especificado
tabela = driver.find_element('xpath', local_tabela)

# Obtém o código HTML da tabela
html_tabela = tabela.get_attribute('outerHTML')

# Lê a tabela HTML e a converte em um DataFrame usando o pandas
# O argumento 'thousands' especifica o caractere usado para separar milhares
# O argumento 'decimal' especifica o caractere usado como separador decimal
tabela = pd.read_html(str(html_tabela), thousands='.', decimal=',')[0]

# Exibe o DataFrame 'tabela' com os dados da tabela extraídos
tabela

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,CSTB4,147.69,0.00,0.00,0.000,"0,00%",0.00,0.00,0.00,0.0,...,0.00,"40,85%","28,98%",2.60,"22,40%","20,11%",0.0,8.420670e+09,0.14,"31,91%"
1,CFLU4,1000.00,0.00,0.00,0.000,"0,00%",0.00,0.00,0.00,0.0,...,0.00,"8,88%","10,72%",1.10,"17,68%","32,15%",0.0,6.035100e+07,0.06,"8,14%"
2,MNSA4,0.47,0.00,0.00,0.000,"0,00%",0.00,0.00,0.00,0.0,...,0.00,"-208,15%","-362,66%",3.63,"-13,50%","145,70%",0.0,-9.105000e+06,-6.52,"-41,11%"
3,MNSA3,0.42,0.00,0.00,0.000,"0,00%",0.00,0.00,0.00,0.0,...,0.00,"-208,15%","-362,66%",3.63,"-13,50%","145,70%",0.0,-9.105000e+06,-6.52,"-41,11%"
4,CSTB3,150.00,0.00,0.00,0.000,"0,00%",0.00,0.00,0.00,0.0,...,0.00,"40,85%","28,98%",2.60,"22,40%","20,11%",0.0,8.420670e+09,0.14,"31,91%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,PRBC4,14.54,502.29,40.26,0.000,"0,00%",0.00,0.00,0.00,0.0,...,0.00,"0,00%","0,00%",0.00,"0,00%","8,02%",0.0,1.176410e+09,0.00,"-6,01%"
982,UBBR4,7.49,610.27,1.99,0.000,"0,00%",0.00,0.00,0.00,0.0,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
983,UBBR11,14.75,1201.81,3.91,0.000,"0,00%",0.00,0.00,0.00,0.0,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
984,UBBR3,18.00,1466.61,4.77,0.000,"0,00%",0.00,0.00,0.00,0.0,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
985,SQIA3,27.19,2726.50,3.74,3.642,"0,20%",1.49,26.87,42.96,-3.7,...,16.38,"8,48%","0,45%",1.44,"4,04%","0,14%",35331000.0,6.397490e+08,0.67,"46,25%"

In [8]:
# Define a coluna 'Papel' como o índice do DataFrame
tabela = tabela.set_index('Papel')

# Seleciona apenas as colunas 'Cotação', 'EV/EBIT', 'ROIC' e 'Liq.2meses'
tabela = tabela[['Cotação', 'EV/EBIT', 'ROIC', 'Liq.2meses']]

# Exibe o DataFrame 'tabela' após as modificações
tabela

        Cotação  EV/EBIT     ROIC  Liq.2meses
Papel
CSTB4    147.69     0.00   22,40%         0.0
CFLU4   1000.00     0.00   17,68%         0.0
MNSA4      0.47     0.00  -13,50%         0.0
MNSA3      0.42     0.00  -13,50%         0.0
CSTB3    150.00     0.00   22,40%         0.0
...         ...      ...      ...         ...
PRBC4     14.54     0.00    0,00%         0.0
UBBR4      7.49     0.00    0,00%         0.0
UBBR11    14.75     0.00    0,00%         0.0
UBBR3     18.00     0.00    0,00%         0.0
SQIA3     27.19    46.75    4,04%  35331000.0

[986 rows x 4 columns]

In [9]:
# Remove o símbolo de porcentagem (%) da coluna 'ROIC'
tabela['ROIC'] = tabela['ROIC'].str.replace("%", "")

# Remove os pontos (.) da coluna 'ROIC'
tabela['ROIC'] = tabela['ROIC'].str.replace(".", "")

# Substitui as vírgulas (,) por pontos (.) na coluna 'ROIC'
tabela['ROIC'] = tabela['ROIC'].str.replace(",", ".")

# Converte a coluna 'ROIC' para o tipo de dado float
tabela['ROIC'] = tabela['ROIC'].astype(float)

# Exibe o DataFrame 'tabela' após as modificações
tabela

C:\Users\dudiz\AppData\Local\Temp\ipykernel_8048\3690121235.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  tabela['ROIC'] = tabela['ROIC'].str.replace(".", "")

        Cotação  EV/EBIT   ROIC  Liq.2meses
Papel
CSTB4    147.69     0.00  22.40         0.0
CFLU4   1000.00     0.00  17.68         0.0
MNSA4      0.47     0.00 -13.50         0.0
MNSA3      0.42     0.00 -13.50         0.0
CSTB3    150.00     0.00  22.40         0.0
...         ...      ...    ...         ...
PRBC4     14.54     0.00   0.00         0.0
UBBR4      7.49     0.00   0.00         0.0
UBBR11    14.75     0.00   0.00         0.0
UBBR3     18.00     0.00   0.00         0.0
SQIA3     27.19    46.75   4.04  35331000.0

[986 rows x 4 columns]

## Fazendo os rankings para conseguir a carteira

In [11]:
# Filtra o DataFrame 'tabela' para incluir apenas as linhas onde 'Liq.2meses' é maior do que 1000000
tabela = tabela[tabela['Liq.2meses'] > 1000000]

# Filtra o DataFrame 'tabela' para incluir apenas as linhas onde 'EV/EBIT' é maior do que 0
tabela = tabela[tabela['EV/EBIT'] > 0]

# Filtra o DataFrame 'tabela' para incluir apenas as linhas onde 'ROIC' é maior do que 0
tabela = tabela[tabela['ROIC'] > 0]

# Exibe o DataFrame 'tabela' após os filtros terem sido aplicados
tabela

       Cotação  EV/EBIT   ROIC   Liq.2meses
Papel
QUAL3     2.85     4.58  13.95   16153100.0
MEGA3     7.81    22.13   3.66    8475680.0
LWSA3     5.43    33.31   2.03   33248300.0
CBAV3     3.71    81.43   0.53   16219900.0
MYPK3    11.15     8.27   6.73   18431400.0
...        ...      ...    ...          ...
RAIL3    22.02    17.20   7.54  325466000.0
ELET6    38.26    14.41   3.61   65885100.0
CEAB3     4.94     6.59   5.28   18531100.0
PTBL3     4.50     9.12   7.36    6024270.0
SQIA3    27.19    46.75   4.04   35331000.0

[188 rows x 4 columns]

In [12]:
# Calcula o ranking do indicador 'EV/EBIT' para todas as empresas em ordem crescente
tabela['ranking_ev_ebit'] = tabela['EV/EBIT'].rank(ascending=True)

# Calcula o ranking do indicador 'ROIC' para todas as empresas em ordem decrescente
tabela['ranking_roic'] = tabela['ROIC'].rank(ascending=False)

# Soma os rankings 'ranking_ev_ebit' e 'ranking_roic' para obter um ranking final
tabela['ranking_final'] = tabela['ranking_ev_ebit'] + tabela['ranking_roic']

# Exibe o DataFrame 'tabela' com as novas colunas de rankings adicionadas
tabela

,Cotação,EV/EBIT,ROIC,Liq.2meses,ranking_ev_ebit,ranking_roic,ranking_final
Papel,,,,,,,
QUAL3,2.85,4.58,13.95,16153100.0,17.0,59.0,76.0
MEGA3,7.81,22.13,3.66,8475680.0,170.0,160.0,330.0
LWSA3,5.43,33.31,2.03,33248300.0,178.0,179.0,357.0
CBAV3,3.71,81.43,0.53,16219900.0,185.0,186.0,371.0
MYPK3,11.15,8.27,6.73,18431400.0,74.0,127.0,201.0
...,...,...,...,...,...,...,...
RAIL3,22.02,17.20,7.54,325466000.0,160.0,122.0,282.0
ELET6,38.26,14.41,3.61,65885100.0,143.0,163.0,306.0
CEAB3,4.94,6.59,5.28,18531100.0,50.5,145.0,195.5
PTBL3,4.50,9.12,7.36,6024270.0,87.0,124.0,211.0
SQIA3,27.19,46.75,4.04,35331000.0,181.0,156.0,337.0

In [13]:
# Ordena o DataFrame 'tabela' com base na coluna 'ranking_final' em ordem crescente
tabela = tabela.sort_values('ranking_final')

# Exibe as 10 primeiras linhas do DataFrame após a ordenação
tabela.head(10)

,Cotação,EV/EBIT,ROIC,Liq.2meses,ranking_ev_ebit,ranking_roic,ranking_final
Papel,,,,,,,
PSSA3,25.26,0.20,60.76,3.332950e+07,1.0,1.0,2.0
PETR4,35.08,2.58,28.95,1.770140e+09,4.0,9.5,13.5
PETR3,38.17,2.74,28.95,4.915640e+08,5.0,9.5,14.5
UNIP6,71.19,4.48,38.68,1.605610e+07,12.0,3.0,15.0
KEPL3,10.35,4.57,43.61,1.295090e+07,16.0,2.0,18.0
WIZC3,5.01,1.88,24.18,4.280200e+06,3.0,16.0,19.0
VLID3,15.69,3.92,20.64,7.194050e+06,8.0,22.0,30.0
GOAU4,10.29,1.32,19.35,7.585830e+07,2.0,30.0,32.0
PLPL3,9.15,5.15,30.59,1.356620e+07,25.0,7.0,32.0
FESA4,48.28,4.66,25.57,8.777320e+06,19.0,14.0,33.0